### PR TITLE
Parquet 优化

### PR DESCRIPTION
**Pull request by baibaichen**
see  [Parquet 优化](https://olapio.atlassian.net/wiki/spaces/PD/pages/1982332988/2020-09-10#Parquet-%E4%BC%98%E5%8C%96)

### CODE REVIEW

**Comment by baibaichen** [comment]
retest this please

**Comment by baibaichen** [comment]
retest this please

**Review by zheniantoushipashi — APPROVED** [review]
LGTM

**Review by lxian — APPROVED** [review]

**Comment by baibaichen** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Parquet MR 1.12.0-kylin-r6:
[INFO]
[INFO] Apache Parquet MR .................................. SUCCESS [  1.079 s]
[INFO] Apache Parquet Format Structures ................... SUCCESS [  1.212 s]
[INFO] Apache Parquet Generator ........................... SUCCESS [  0.273 s]
[INFO] Apache Parquet Common .............................. SUCCESS [  1.239 s]
[INFO] Apache Parquet Encodings ........................... SUCCESS [  9.112 s]
[INFO] Apache Parquet Column .............................. SUCCESS [  9.522 s]
[INFO] Apache Parquet Arrow ............................... SUCCESS [  0.774 s]
[INFO] Apache Parquet Jackson ............................. SUCCESS [  0.212 s]
[INFO] Apache Parquet Hadoop .............................. SUCCESS [ 40.248 s]
[INFO] Apache Parquet Avro ................................ SUCCESS [ 10.487 s]
[INFO] Apache Parquet Benchmarks .......................... SUCCESS [  0.318 s]
[INFO] Apache Parquet Pig ................................. SUCCESS [ 17.068 s]
[INFO] Apache Parquet Thrift .............................. SUCCESS [  8.039 s]
[INFO] Apache Parquet Cascading ........................... SUCCESS [ 38.088 s]
[INFO] Apache Parquet Cascading (for Cascading 3.0 onwards) SUCCESS [ 38.636 s]
[INFO] Apache Parquet Command-line ........................ SUCCESS [  0.419 s]
[INFO] Apache Parquet Pig Bundle .......................... SUCCESS [  0.214 s]
[INFO] Apache Parquet Protobuf ............................ SUCCESS [  8.358 s]
[INFO] Apache Parquet Scala ............................... SUCCESS [  1.226 s]
[INFO] Apache Parquet Scrooge ............................. SUCCESS [ 43.287 s]
[INFO] Apache Parquet Hadoop Bundle ....................... SUCCESS [  0.237 s]
[INFO] Apache Parquet Hive ................................ SUCCESS [  0.064 s]
[INFO] Apache Parquet Hive Binding Parent ................. SUCCESS [  0.043 s]
[INFO] Apache Parquet Hive Binding Interface .............. SUCCESS [  0.222 s]
[INFO] Apache Parquet Hive 0.10 Binding ................... SUCCESS [  0.368 s]
[INFO] Apache Parquet Hive 0.12 Binding ................... SUCCESS [  0.297 s]
[INFO] Apache Parquet Hive Binding Factory ................ SUCCESS [  0.324 s]
[INFO] Apache Parquet Hive Binding Bundle ................. SUCCESS [  0.224 s]
[INFO] Apache Parquet Hive Storage Handler ................ SUCCESS [  0.879 s]
[INFO] Apache Parquet Hive Bundle ......................... SUCCESS [  0.193 s]
[INFO] Apache Parquet Tools ............................... SUCCESS [  1.371 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:54 min
[INFO] Finished at: 2020-10-14T16:28:26+08:00
[INFO] ------------------------------------------------------------------------

  ~/SourceCode/parquet-mr     kyparquet-1.12.x-4.x 

**Pull request merged**
